### ISSUE TITLE
More captures shown in our pywb as compared to AIT environment

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-pywb#103]
Only 1 capture shown for Jun 13, 2022 in AIT
https://wayback.archive-it.org/8751/*/https://www.stanfordeugenics.com/
![Screen Shot 2022-07-13 at 10 23 48 AM](https://user-images.githubusercontent.com/1050899/178794459-1fb5e9e4-98ff-4121-a0f5-9656a07308f0.png)

2 captures shown for  Jun 13, 2022 in our pywb
https://swap.stanford.edu/was/*?url=https%3A%2F%2Fwww.stanfordeugenics.com%2F

![Screen Shot 2022-07-13 at 10 25 59 AM](https://user-images.githubusercontent.com/1050899/178794471-4b5e2066-84a1-48fe-b778-a78917fffed3.png)

**Comment by peterchanws** [comment]
If the 2 captures are the same, we should just show 1 to users.

**Comment by justinlittman** [comment]
They have different file checksums. How would you suggest determining sameness?

**Comment by lwrubel** [comment]
@peterchanws Archive-It's documentation says that they are collapsing the results (see "[Collapse results](https://support.archive-it.org/hc/en-us/articles/115001790023-Access-Archive-It-s-Wayback-index-with-the-CDX-C-API)" and that the calendar does that by default.)

Both pywb and the underlying CDX index that Archive-It uses have the same information. Pywb is reflecting accurately what is in the index. It's possible that Archive-It's crawler returned to a page to capture files that were missed.

I'll close this ticket since it appears that there is just a difference in the replay tools, not any data loss or duplication.
