### ISSUE TITLE
Migrate to GA4

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-pywb#158]
Universal Analytics (UA) properties will [stop collecting data as of July 1, 2023](https://support.google.com/analytics/answer/11583528?hl=en). The data in the existing UA property will remain available for an unspecified period of time. In order to collect data after July 1, 2023 we will need to create a new GA4 property and add the newer `gtag.js` snippet to the application in order to collect data into the new GA4 property.

- [x] [Add a Google Analytics 4 property](https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article)
- [x] [Add the Google tag to the application](https://support.google.com/analytics/answer/9304153#zippy=%2Cadd-your-tag-using-google-tag-manager%2Cadd-the-google-tag-directly-to-your-web-pages)
- [x] [Set up event tracking as desired](https://support.google.com/analytics/answer/11091025#zippy=%2Cin-this-article). NOTE: _everything_ is an event in GA4 and it automatically collects some events.
- [ ] Optionally, download and archive the historical UA data.

NOTE: There is currently a [setting available](https://support.google.com/analytics/answer/11150547) that will send events from `analytics.js` (UA) to GA4 properties. However, Google does not guarantee this will continue to work after July 1, 2023. This is not recommended as a migration path for event tracking.

**Comment by edsu** [comment]
I started by adding the GA4 property following the instructions. Unfortunately my account doesn't appear to have permission to *Create a new Google Analytics Property*.  Does anyone know who who the administrator is?

<img width="1814" alt="Screenshot 2023-02-03 at 5 50 05 PM" src="https://user-images.githubusercontent.com/33829/216726125-a84771c7-68c4-425c-8cfe-eb2adcd2b736.png">

**Comment by edsu** [comment]
@marlo-longley set me up with access so I was able to create the new GA4 property for `swap.stanford.edu`.

In the process of testing I noticed that the archive view e.g. https://swap.stanford.edu/was/20140510140817/http://apod.nasa.gov/apod/astropix.html currently lacks the Google Analytics embed. This is because, as the [docs](https://pywb.readthedocs.io/en/latest/manual/template-guide.html#base-templates-and-supporting-templates) explain, there is an additional template that the JavaScript needs to be added to `frame_insert.html` as well.  So I am going to customize that as part of this work.
