### ISSUE TITLE
Replay issue: background image disappears

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was-pywb#70]
When replaying this page the background image disappears:

https://was-pywb-prod.stanford.edu/was/20210128000826/https://www.theaaas2020project.com/about

You can see it displaying correctly in current production swap.stanford.edu:

https://swap.stanford.edu/20210128000826/https://www.theaaas2020project.com/about

@peterchanws believes that the image appeared before on was-pywb-prod

**Comment by edsu** [comment]
This was an interesting one. Examining the HTTP requests in the Browser DevTools I can see that the background image is coming from the live web:

https://static.wixstatic.com/media/2c6b0a_8191471c01ec46ceb607ea4a2568a264~mv2.jpg/v1/fill/w_2830,h_1928,al_c,q_90,usm_0.66_1.00_0.01/2c6b0a_8191471c01ec46ceb607ea4a2568a264~mv2.webp

This is known as a live leak, when JavaScript escapes the OpenWayback interface and starts getting things from the liveweb. The image was not archived when this page was crawled.

pywb on the otherhand doesn't allow for this liveleak to happen because it intercepts JavaScript calls to the web and routes them back to the web archive. Since this image wasn't archived it comes back as a 404 error:

https://was-pywb-prod.stanford.edu/was/20210128000826im_/https://static.wixstatic.com/media/2c6b0a_8191471c01ec46ceb607ea4a2568a264~mv2.jpg/v1/fill/w_1415,h_964,al_c,q_85,usm_0.66_1.00_0.01/2c6b0a_8191471c01ec46ceb607ea4a2568a264~mv2.webp

So the good news is that pywb doesn't allow these live leaks to the live web, but in this case it leads to a poorer render since the image has not been archived. In this case we could try to archive that one image, put it in a one-time registration and it should start to work again? It might be worth an experiment.

**Comment by mjgiarlo** [comment]
@edsu do you think this should block the production switch?

**Comment by peterchanws** [comment]
Thanks, Ed, for the explanation.
